apiVersion: v1
kind: Pod
spec:
  containers:
  - image: gdelbrusco/proftpd
    imagePullPolicy: Always
    name: proftpd-test
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      runAsNonRoot: false
    stdin: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /configfile/hidden.conf
      name: vol1
      subPath: hidden.conf
    - mountPath: /data/group/
      name: vol2
    - mountPath: /data/authuserfile/
      name: vol3
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-j4b2m
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 256
      name: hiddenconf
      optional: false
    name: vol1
  - configMap:
      defaultMode: 416
      name: group-proftpd
      optional: false
    name: vol2
  - configMap:
      defaultMode: 416
      name: authuserfile
      optional: false
    name: vol3